name: Test Python before push

# Déclenche le workflow à chaque push ou pull request sur la branche main
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run tests

      
        run: python3 -m unittest test.py  